# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pr:
- master

pool:
  vmImage: 'ubuntu-16.04'

resources:
  containers:
    - container: jekyll 
      image: jekyll/builder:3.8

steps:
# Build Jekyll Website
#
- script: echo hello

- script: |
    mkdir _site
    touch Gemfile.lock
    chmod a+w Gemfile.lock
    jekyll build

# Copy Website to Storage Acct# Copy Website to Storage Acct
# Azure CLI
# Publish website to ACI
- task: AzureCLI@1
  displayName: Copy data to storage acct
  inputs:
    azureSubscription: imperfect
    scriptLocation: inlineScript
    inlineScript: |
      echo "Running az script."
      az storage blob upload-batch \
        --destination \$web \
        --account-name "azurepatterns" \
        --source "_site"

- task: CopyFiles@2
  inputs:
    contents: '_site/**'
    targetFolder: $(Build.ArtifactStagingDirectory)

#- task: UniversalPackages@0
#  displayName: Universal Publish
#  inputs:
#    command: publish
#    publishDirectory: '$(Build.ArtifactStagingDirectory)'
#    vstsFeedPublish: 'www-imperfect'
#    vstsFeedPackagePublish: 'www'
#    packagePublishDescription: 'Website Build'
#    versionOption: patch
    #versionPublish: $(setVar.commitHash)

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)
    artifactName: WWWBuildOutput

#Purge CDN to update content
- task: AzureCLI@1
  displayName: purge CDN contents
  inputs:
    azureSubscription: imperfect
    scriptLocation: inlineScript
    inlineScript: |
       echo "Purging cdn content"
       az cdn endpoint purge \
        --name azurepatterns \
        --profile-name azurepatternscdn \
        --resource-group azurepatterns \
        --content-paths '/*'

